inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake

Metrics/MethodLength:
  Max: 25

Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 3

Style/SymbolArray:
  EnforcedStyle: brackets
